name: Deploy Functions on Merge

on:
  push:
    branches:
      - main  # Ana dalın ismi 'master' ise burayı değiştir
    paths:
      - 'functions/**' # Sadece functions klasörü değişirse çalışsın

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek (Checkout Repo)
        uses: actions/checkout@v4

      - name: Node.js Kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Functions için kullandığın Node sürümü

      - name: Bağımlılıkları Yükle
        run: cd functions && npm ci

      - name: Firebase'e Deploy Et
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAMPUS_FORUM }}